name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-rust
      - name: Check
        run: cargo check
  test:
    name: Test
    runs-on: "ubuntu-latest"
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-rust
      - name: Run cargo test
        run: cargo test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-rust
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      - name: Install cargo deny
        run: cargo install cargo-deny
      - name: Run cargo clippy
        run: cargo deny check
      
  build_non_macos:
    needs:
      - check
      - test
      - lint
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, x86_64-pc-windows-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build binaries in release mode
        run: cross build --release --target ${{ matrix.target }}
      - name: Upload release artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: loadtest-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*

  build_macos:
    needs:
      - check
      - test
      - lint
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-rust
        with:
          target: ${{ matrix.target }}
      - name: Build binaries in release mode
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload release artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: loadtest-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
